### PR TITLE
Initial PR started for RIP 6

### PR DESCRIPTION
**Pull request by dekanbro**

### CODE REVIEW

**Comment by nsward** [comment]
Made a first pass of what the shim contract could look like [here](https://gist.github.com/nsward/885308feaaad9124b8d930a75f560c99). There are a few different routes we could go, but this one is probably the simplest that still serves a useful purpose. It does not support multiple atomic calls, but does support calls with value and arbitrary data and maintains a permanent address so the actor can hold token balances, etc.

Here's what an execution would look like:
1. Deploy a `MolochActor` contract (this only needs to be deployed once, but you could deploy multiple actors for a Moloch)
2. Submit and pass a proposal with `applicant == address(molochActor)` and in the `details` field include the parameters of the call that the `MolochActor` should make with the following encoding (or similar): `{32 byte nonce}{20 byte target address}{32 byte value}{data}`
3. Execute `MolochActor.call()` with the parameters of the call and the `proposalId` of the passing moloch proposal
4. `MolochActor` checks that the call parameters match the proposed parameters and that the moloch proposal passed, then executes the call

# Issues
Well.. it doesn't compile. Solidity makes it exceptionally difficult to pass structs via functions, and one of the major limitations of this is that automatically generated getters for `mapping (type => Struct) public` will not return any arrays in the struct. This poses a problem, because we can't get `proposal.flags`, so we can't tell whether the proposal has passed. I'll do some solidity wrangling and see how we can hack around this.

In the meantime, any thoughts on the draft @dekanbro @proofoftom? Particularly on whether this is too complex for a reasonable first iteration of the interface for interacting with the shims.

**Comment by proofoftom** [comment]
> automatically generated getters for mapping (type => Struct) public will not return any arrays in the struct

Indeed, I'm thinking we'll need something along the lines of `checkHasPassed() public view returns (bool) { return hasPassed; }` which loops over the array of flags and returns false if any are set.

**Comment by nsward** [comment]
@proofoftom I just updated the gist with the working version. The whole `(,,,,,,,,,,,oneMemberOfStruct) = ...` pattern is ugly and a bit unsafe in my opinion (reliant on Moloch not to change the order of parameters in the struct). But, I'm not sure solidity provides a better option.

I'm not actually sure what you mean by looping over the array of flags and returning false if any are set.

**Comment by proofoftom** [comment]
Heh yeah disregard. I was going to suggest the direction that you took with getProposalFlags but must've had a brain fart along the way :p

**Comment by oovg** [comment]
Can this issue be closed?

**Pull request closed without merging**
