### PR TITLE
added RIP 71 MD in PROPOSALS

### PR DESCRIPTION
**Pull request by bitbeckers**
Added MarkDown file to wrap up RIP. MarkDown covers proposal and deliverables

### CODE REVIEW

**Review by plor — COMMENTED** [review]
I don't know whether the RIP number should be the issue number. So far they have all been incremental with no skips. This might be confusing, so maybe your naming is the right approach.

**Comment by bitbeckers** [comment]
@plor so what should we do? I just went with what I know from EIPs so maybe my bad

**Comment by plor** [comment]
I think switch to rip-30. It is tricky to break a pattern once it is established, even if it breaks a pattern it was based on.

**Comment by bitbeckers** [comment]
@plor done!

**Review by plor — APPROVED** [review]

**Pull request merged**
